spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/students
    username: postgres
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
flyway:
  baselineOnMigrate: true
  url: jdbc:postgresql://localhost:5432
  schema: students
  user: postgres
  password: admin
